name: "Manual: Check Reaction Status"

on:
  workflow_dispatch:

jobs:
  check-reactions:
    uses: ./.github/workflows/slack-ploughshare.yml
    secrets: inherit
    with:
      command: 'check-reactions'
      dry_run: true
      additional_flags: ''
