name: "Manual: View Warning Tracker Status"

on:
  workflow_dispatch:

jobs:
  view-report:
    uses: ./.github/workflows/slack-ploughshare.yml
    secrets: inherit
    with:
      command: 'warning-report'
      dry_run: true
      additional_flags: ''
