name: "Manual: Test Archive (Dry Run)"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-archive:
    uses: ./.github/workflows/slack-ploughshare.yml
    secrets: inherit
    with:
      command: 'auto-archive'
      dry_run: true
      additional_flags: ''
