name: "Manual: Test Warnings (Dry Run)"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-warnings:
    uses: ./.github/workflows/slack-ploughshare.yml
    secrets: inherit
    with:
      command: 'send-warnings'
      dry_run: true
      additional_flags: ''
