name: "Test: Dry Run Warnings"

on:
  workflow_dispatch:

jobs:
  test-warnings:
    uses: ./.github/workflows/slack-ploughshare.yml
    secrets: inherit
    with:
      command: 'send-warnings'
      dry_run: true
      additional_flags: ''
